import type { Metadata } from 'next';
import { Space_Grotesk, Space_Mono, Geist } from 'next/font/google';
import './globals.css';
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const spaceGrotesk = Space_Grotesk({
    variable: '--font-space-grotesk',
    subsets: ['latin'],
});

const spaceMono = Space_Mono({
    variable: '--font-space-grotesk-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn("h-full", "antialiased", spaceGrotesk.variable, spaceMono.variable, "font-sans", geist.variable)}
        >
            <body className="min-h-full flex flex-col">{children}</body>
        </html>
    );
}
